"""Cart update

Revision ID: 9ee404aea0df
Revises: b55e4c5845aa
Create Date: 2023-11-13 15:30:47.825950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ee404aea0df'
down_revision = 'b55e4c5845aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datecreated', sa.DateTime(), nullable=False))
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('datecreated')

    # ### end Alembic commands ###
